#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xrandr --dpi 84
(sleep 1 && xcompmgr) &

autostart="dunst pipewire sblocks"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

station portable
risgrot -s "$XDG_DATA_HOME/wall" -t gruvbox -q &

while type dwm >/dev/null ; do dwm && continue || break ;done

